version: '3.8'

services:
  gateway-dev:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile.dev
    depends_on:
      - gateway-db-dev
      - gateway-redis-dev
    image: lorenzofaivre/project-boilerplate/gateway-dev:latest
    restart: always
    ports:
      - 0.0.0.0:4000:4000
    volumes:
      - ./gateway:/gateway
      - ./gateway/dist:/gateway/dist
      - ./gateway/node_modules:/gateway/node_modules
    environment:
      - GATEWAY_DEV_HOST=gateway-dev
      - GATEWAY_DEV_HOST_EXT=0.0.0.0
      - GATEWAY_DEV_PORT=4000
  gateway-db-dev:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gateway-db-dev
    volumes:
      - gateway-db-data-dev:/var/lib/postgresql/data
  gateway-redis-dev:
    image: redis:6.0.5-alpine
    restart: always
    ports:
      - 6379:6379

  gateway-test:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile.test
    depends_on:
      - gateway-db-test
    image: lorenzofaivre/project-boilerplate/gateway-test:latest
    restart: always
    ports:
      - 3002:3002
  gateway-db-test:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gateway-db-test
    volumes:
      - gateway-db-data-test:/var/lib/postgresql/data

  tests:
    build:
      context: .
      dockerfile: ./tests/Dockerfile.dev
    depends_on:
      - gateway-test
    image: lorenzofaivre/project-boilerplate/tests:latest
    restart: on-failure
    ports:
      - 8000:8000
    volumes:
      - ./tests:/tests
      - ./tests/node_modules:/tests/node_modules
    environment:
      - GATEWAY_TEST_HOST=host.docker.internal
      - GATEWAY_TEST_PORT=3002

volumes:
  gateway-db-data-dev:
  gateway-db-data-test:
