version: '3.8'

services:
  gateway-dev:
    build:
      context: ./gateway
      dockerfile: Dockerfile.dev
    depends_on:
      - gateway-db-dev
      - gateway-redis-dev
    image: lorenzofaivre/project-boilerplate/gateway-dev:latest
    restart: always
    ports:
      - 0.0.0.0:4000:4000
    volumes:
      - ./gateway:/usr/src/gateway:delegated
    environment:
      - GATEWAY_DEV_HOST=gateway-dev
      - GATEWAY_DEV_HOST_EXT=0.0.0.0
      - GATEWAY_DEV_PORT=4000
      - GATEWAY_DEV_REDIS_HOST=gateway-redis-dev
      - GATEWAY_DEV_REDIS_PORT=6379
      - SPARKPOST_API_KEY=$SPARKPOST_API_KEY
      - SESSION_SECRET=$SESSION_SECRET
      - TWITTER_CONSUMER_KEY=$TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET=$TWITTER_CONSUMER_SECRET
  gateway-db-dev:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gateway-db-dev
  gateway-redis-dev:
    image: redis:6.0.5-alpine
    restart: always
    ports:
      - 6379:6379

  gateway-test:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile.test
    depends_on:
      - gateway-db-test
      - gateway-redis-test
    image: lorenzofaivre/project-boilerplate/gateway-test:latest
    restart: always
    ports:
      - 0.0.0.0:3002:3002
    environment:
      - GATEWAY_DEV_HOST=gateway-test
      - GATEWAY_DEV_HOST_EXT=0.0.0.0
      - GATEWAY_DEV_PORT=3002
      - GATEWAY_DEV_REDIS_HOST=gateway-redis-test
      - GATEWAY_DEV_REDIS_PORT=6379
  gateway-db-test:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gateway-db-test
  gateway-redis-test:
    image: redis:6.0.5-alpine
    restart: always
    ports:
      - 6379:6379

  tests:
    build:
      context: .
      dockerfile: ./tests/Dockerfile.dev
    depends_on:
      - gateway-dev
    image: lorenzofaivre/project-boilerplate/tests:latest
    restart: 'no'
    volumes:
      - ./tests:/tests:ro,delegated
    environment:
      - GATEWAY_TEST_HOST=gateway-dev
      - GATEWAY_TEST_HOST_EXT=0.0.0.0
      - GATEWAY_TEST_PORT=4000
