FROM node:12.18.1-alpine

RUN apk add --no-cache openssl

ENV NODE_ENV=development
ENV DOCKERIZE_VERSION v0.6.1

WORKDIR /server

COPY package*.json /server/
RUN npm install

COPY . /server

EXPOSE 4000

RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
  && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
  && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

CMD dockerize -wait tcp://db:5432 -timeout 60m npm run start:dev